# NUMPY OPERATIONS

Note: as with standard Python, most NumPy functions exist as instance methods of the ndarray.

so we can call them both ways (for most cases):\
np.functionname(arrayname, [optional parameters])\
arrayname.methodname([optional parameters])

In [2]:
import numpy as np

# VECTORIZATION

The name given to the technnique whereby Numpy array operations are performed element by element 

## ARRAY ARITHMETIC

Let's first see a few simple math examples.\
In the next section we will see that +-*/ are just short hand for ufuncs.

In [3]:
xarr =np.array([[1,1,1,1],[2,2,2,2]])
print(xarr)
xarr * xarr

[[1 1 1 1]
 [2 2 2 2]]


array([[1, 1, 1, 1],
       [4, 4, 4, 4]])

In [80]:
xarr/xarr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
xarr + 5

array([[6, 6, 6, 6],
       [7, 7, 7, 7]])

In [82]:
xarr

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [83]:
yarr=[3,3,3,3]

xarr + yarr

array([[4, 4, 4, 4],
       [5, 5, 5, 5]])

## UNIVERSAL FUNCTIONS UFUNCS - VECTORIZATION

Mathematial operations in numpy are done using ufuncs

These functions include standard arithmetic and trigonometric functions, functions for arithmetic operations, handling complex numbers, statistical functions etc

Properties
- they operate on ndarray, element by element
- some ufuncs are called automatically when the corresponding arithmetic operator is called (np.add(x, 5)) is called for x+5 where x is an ndarray
- they exist in two flavors: **unary** ufuncs (operate on one array) and **binary** ufuncs (operate on two arrays)

NOTE: even though Python has similar named functions()- min, max, they are different from the numpy versions (np.max() and np.min()).

In [9]:
#The key to making NumPy operations fast is the use of 
#vectorized operations (element by element).

## Arithmetic operations


In [11]:
x = np.arange(4)
print(x)

[0 1 2 3]


In [14]:
print(x+5)
print(x-5)
print(x*5)
print(x/5)
print(x//2)  # floor divide
print(-x)
print(x%2)
print(x**2)  # x raised to power 2
print(x*x)   # because of vectorization, same result as above

[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 0 1]
[0 1 4 9]
[0 1 4 9]


In [15]:
#These arithmetic operations are simply convenient wrappers 
#around specific functions built into NumPy.
#For example, the + operator is a wrapper for the add function

In [18]:
# the equivalent unfuncs

print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,5))
print(np.divide(x,5))
print(np.floor_divide(x,2))  # floor divide
print(np.negative(x))
print(np.mod(x,2))
print(np.power(x,2))
print(np.multiply(x,x))


[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 0 1]
[0 1 4 9]
[0 1 4 9]


In [32]:
print(np.round(np.divide(x,2) + 3))

[3. 4. 4. 4.]


In [148]:
new = np.array([[0,-2,4,-6,8]])
print(np.abs(new/10))

# calling just abs(q[[0,2,4,6,8]]/10) will call numpy's absolute() function internally

[[0.  0.2 0.4 0.6 0.8]]


# BROADCASTING

Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.

When arays are of same size, straightforward to apply element by element operations. 

Broadcasting extends the arrays as needed to make it work on arrays of diff shape

In [4]:
M = np.ones((2, 3))       
N = np.arange(3)
print(M)
print(N)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [5]:
print(M.shape)
print(N.shape)
#Broadcasting happens to change N to (1,3)
#and then N is extended to (2,3) and then added to M

M+N

(2, 3)
(3,)


array([[1., 2., 3.],
       [1., 2., 3.]])

# STRUCTURED DATA

NumPy also has some support for structured data (like tables in excel or a spreadsheet) with optional field /column names.

But these are best handled using Pandas.